
<div class="content-header">
<table cellspacing="0">
    <tr>
        <td style="width:50%;"><h3 class="icon-head head-orders"><?php echo Mage::helper('integracommerce')->__('Integracommerce Orders') ?></h3></td>
        <td class="a-right">

        	<?php $this->_addButton('add_new', array(
        										'label'   => Mage::helper('integracommerce')->__('Integrate'),
        										'onclick' => 'setLocation(\'' . $this->getUrl('integracommerce/adminhtml_orders/integrate') . '\')',
        										'class'   => 'add'
    											));  
    		?>

            <?php echo $this->getButtonsHtml() ?>
        </td>
    </tr>
</table>
</div>

<div>
    <?php echo $this->getGridHtml() ?>
</div>
